[package]
name = "rs2py"
version = "0.1.0"
authors = ["roger"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpython = { version = "0.5", features = ["extension-module"] }
